terminal_background = 'p:t-background'
console_title_template = '{{ .User }} in Terminal'
version = 3
final_space = true

[palette]
  blue-bell = '#9aa5ce'
  blue-black = '#394260'
  celeste-blue = '#89DDFF'
  dark-blue-grey = '#212736'
  dark-grey = '#090c0c'
  light-blue = '#769ff0'
  light-grey = '#e3e5e5'
  light-sky-blue = '#89DDFF'
  main-bg = '#090B10'
  pastal-grey = '#cfc9c2'
  pistachio-green = '#C3E88D'
  t-background = 'p:main-bg'
  terminal-black = '#464B5D'
  terminal-blue = '#82AAFF'
  terminal-green = '#C3E88D'
  terminal-magenta = '#C792EA'
  terminal-red = '#F07178'
  terminal-white = '#FFFFFF'
  terminal-yellow = '#FFCB6B'
  white-blue = '#a3aed2'
  white-grey = '#a0a9cb'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '░▒▓'
    foreground = 'p:white-blue'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  '
    foreground = 'p:dark-grey'
    background = 'p:white-blue'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ''
    foreground = 'p:white-blue'
    background = 'p:light-blue'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = 'p:light-grey'
    background = 'p:light-blue'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = ''
      folder_separator_icon = '  '
      max_depth = 2
      style = 'agnoster_short'

  [[blocks.segments]]
    template = ''
    foreground = 'p:light-blue'
    background = 'p:terminal-black'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    foreground = 'p:white-grey'
    background = 'p:terminal-black'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
    template = ''
    foreground = 'p:terminal-black'
    background = 'p:dark-blue-grey'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .CurrentDate | date .Format }}'
    foreground = 'p:white-grey'
    background = 'p:dark-blue-grey'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      time_format = '3:04 PM'

  [[blocks.segments]]
    template = ''
    foreground = 'p:dark-blue-grey'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'rprompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    template = '~{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 2500

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'p:pistachio-green'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = 'p:terminal-blue'
    type = 'dotnet'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }}'
    foreground = '#terminal-magenta'
    type = 'java'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'p:terminal-blue'
    type = 'php'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '\uE235 {{ .Full }}'
    foreground = 'p:terminal-yellow'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '\uE624 {{ .Full }}'
    foreground = 'p:terminal-magenta'
    type = 'julia'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '\uE791 {{ .Full}}'
    foreground = 'p:terminal-red'
    type = 'ruby'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '\uFCD1 {{ .Full}}'
    foreground = 'p:light-sky-blue'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    foreground = 'p:white-blue'
    type = 'command'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      command = 'git log --pretty=format:%cr -1 || date +%H:%M:%S'
      shell = 'bash'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ''
    foreground = 'p:terminal-magenta'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
