version = 2
final_space = true
console_title_template = '{{ .User }} in Terminal'
terminal_background = 'p:t-background'

[palette]
main-bg = '#090B10'
terminal-red = '#F07178'
pistachio-green = '#C3E88D'
terminal-green = '#C3E88D'
terminal-yellow = '#FFCB6B'
terminal-blue = '#82AAFF'
celeste-blue = '#89DDFF'
light-sky-blue = '#89DDFF'
terminal-white = '#FFFFFF'
white-blue = '#a3aed2'
blue-bell = '#9aa5ce'
light-blue = '#769ff0'
light-grey = '#e3e5e5'
dark-grey = '#090c0c'
dark-blue-grey = '#212736'
pastal-grey = '#cfc9c2'
terminal-magenta = '#C792EA'
blue-black = '#394260'
terminal-black = '#464B5D'
white-grey = '#a0a9cb'
t-background = 'p:main-bg'

[[blocks]]
type = 'prompt'
alignment = 'left'

  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  background = 'transparent'
  foreground = 'p:white-blue'
  template = '░▒▓'
   
  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  background = 'p:white-blue'
  foreground = 'p:dark-grey'
  template = '  '
   
  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  background = 'p:light-blue'
  foreground = 'p:white-blue'
  template = ''
   
  [[blocks.segments]]
  type = 'path'
  style = 'powerline'
  foreground = 'p:light-grey'
  background = 'p:light-blue'
  properties.folder_icon = ''
  properties.folder_separator_icon = '  '
  properties.max_depth = 2
  properties.style = 'agnoster_short'
  template = ' {{ .Path }} '
   
  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  background = 'p:terminal-black'
  foreground = 'p:light-blue'
  template = ''
  
  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:white-grey'
    background = 'p:terminal-black'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ' '
      commit_icon = '@'
      fetch_status = true
 
  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  background = 'p:dark-blue-grey'
  foreground = 'p:terminal-black'
  template = ''
   
  [[blocks.segments]]
  type = 'time'
  style = 'plain'
  background = 'p:dark-blue-grey'
  foreground = 'p:white-grey'
  properties.time_format = '3:04 PM'
  template = '  {{ .CurrentDate | date .Format }}'
   
  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  background = 'transparent'
  foreground = 'p:dark-blue-grey'
  template = ''
 
[[blocks]]
type = 'rprompt'
alignment = 'right'
overflow = 'hide'

  [[blocks.segments]]
  type = 'executiontime'
  style = 'plain'
  foreground = 'yellow'
  background = 'transparent'
  template = '~{{ .FormattedMs }}'

    [blocks.segments.properties]
    threshold = 2500 
 
  [[blocks.segments]]
  type = 'node'
  style = 'plain'
  foreground = 'p:pistachio-green'
  template = ' {{ .Full }} '
   
  [[blocks.segments]]
  type = 'dotnet'
  style = 'plain'
  foreground = 'p:terminal-blue'
  template = '  {{ .Full }} '
   
  [[blocks.segments]]
  type = 'java'
  style = 'plain'
  foreground = '#terminal-magenta'
  template = '  {{ .Full }}'
  
  [[blocks.segments]]
  type = 'php'
  style = 'plain'
  foreground = 'p:terminal-blue'
  template = ' {{ .Full }} '
  
  [[blocks.segments]]
  type = 'python'
  style = 'plain'
  foreground = 'p:terminal-yellow'
  template = '\uE235 {{ .Full }}'
  
  [[blocks.segments]]
  type = 'julia'
  style = 'plain'
  foreground = 'p:terminal-magenta'
  template = '\uE624 {{ .Full }}'
  
  [[blocks.segments]]
  type = 'ruby'
  style = 'plain'
  foreground = 'p:terminal-red'
  template = '\uE791 {{ .Full}}'
  
  [[blocks.segments]]
  type = 'go'
  style = 'plain'
  foreground = 'p:light-sky-blue'
  template = '\uFCD1 {{ .Full}}'
  
  [[blocks.segments]]
  type = 'command'
  style = 'plain'
  foreground = 'p:white-blue'
  properties.command = 'git log --pretty=format:%cr -1 || date +%H:%M:%S'
  properties.shell = 'bash'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  foreground = 'p:terminal-magenta'
  template = ''
